### ISSUE TITLE
Add Test cases and implementation

### ISSUE THREAD

**Issue by muguira-james** [rossgore/iPoet#8]
Should have 3 tests for each function.  There are 2 functions: Search and Eval

Is there an R test harness?

**Comment by rossgore** [comment]
http://r-pkgs.had.co.nz/tests.html - for a really nice overview

testthat is the package we will want to use, mostly I think we just want to make use of the expect functions as needed. More documentation for testthat is here: https://www.rdocumentation.org/packages/testthat/versions/2.0.1

**Comment by muguira-james** [comment]
closes issue #8
